### ISSUE TITLE
Checklist for Android App

### ISSUE THREAD

**Issue by nglphucvinh** [lefeno/lab_iot#1]
- [ ] ListView for Pots List
   - [ ] StatusView (Pot, Area, Humidity)
   - [ ] ArrayAdapter List
- [ ] Notifications when Dehydrated
   - [ ] Show detail information (What pot, Current Humidity...)
   - [ ] Option to Water (all?)
- [ ] DetailView for Each Pot
   - [ ] InformationView (Plant type, Pot ID...)
   - [ ] GraphView
   - [ ] SettingView
